config/routes.rb
Rails.application.routes.draw do
  resources :roles

  devise_for :users
  get 'home/index'
  root to: 'home#index'

  resources :confirm_shows
  resources :confirm_edits
  resources :confirm_deletes
  resources :ussd_logs
  resources :trackers
  resources :tmp_contacts
  resources :contacts
  
  devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end
  
  post 'create_user' => 'users#create', as: :create_user
  get '/users' => 'users#index'
  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/users/:id' => 'users#reset_password', :as => 'reset_password'
  
  
  
  
  
  get       'enable_contact'    =>  'contacts#enable_contact'
  get       'disable_contact'   =>  'contacts#disable_contact'
  
  get       'enable_log'    =>  'ussd_logs#enable_log'
  get       'disable_log'   =>  'ussd_logs#disable_log'
  
  get       'enable_user'    =>  'users#enable_user'
  get       'disable_user'   =>  'users#disable_user'
  
  get       'enable_role'    =>  'roles#enable_role'
  get       'disable_role'   =>  'roles#disable_role'
  
  
  

end

app/models/tmp_contact.rb
class TmpContact < ActiveRecord::Base
end

app/controllers/tmp_contacts_controller.rb
class TmpContactsController < ApplicationController
  before_action :set_tmp_contact, only: [:show, :edit, :update, :destroy]

  # GET /tmp_contacts
  # GET /tmp_contacts.json
  def index
    @tmp_contacts = TmpContact.all
  end

  # GET /tmp_contacts/1
  # GET /tmp_contacts/1.json
  def show
  end

  # GET /tmp_contacts/new
  def new
    @tmp_contact = TmpContact.new
  end

  # GET /tmp_contacts/1/edit
  def edit
  end

  # POST /tmp_contacts
  # POST /tmp_contacts.json
  def create
    @tmp_contact = TmpContact.new(tmp_contact_params)

    respond_to do |format|
      if @tmp_contact.save
        format.html { redirect_to @tmp_contact, notice: 'Tmp contact was successfully created.' }
        format.json { render :show, status: :created, location: @tmp_contact }
      else
        format.html { render :new }
        format.json { render json: @tmp_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tmp_contacts/1
  # PATCH/PUT /tmp_contacts/1.json
  def update
    respond_to do |format|
      if @tmp_contact.update(tmp_contact_params)
        format.html { redirect_to @tmp_contact, notice: 'Tmp contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @tmp_contact }
      else
        format.html { render :edit }
        format.json { render json: @tmp_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tmp_contacts/1
  # DELETE /tmp_contacts/1.json
  def destroy
    @tmp_contact.destroy
    respond_to do |format|
      format.html { redirect_to tmp_contacts_url, notice: 'Tmp contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tmp_contact
      @tmp_contact = TmpContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tmp_contact_params
      params.require(:tmp_contact).permit(:FIRSTNAME, :LASTNAME, :PHONE_NUM, :AGE, :GENDER, :MOBILE_NUMBER, :STATUS, :SESSION_ID)
    end
end

app/helpers/tmp_contacts_helper.rb
module TmpContactsHelper
end

app/views/tmp_contacts/_form.html.erb
<%= simple_form_for(@tmp_contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :FIRSTNAME %>
    <%= f.input :LASTNAME %>
    <%= f.input :PHONE_NUM %>
    <%= f.input :AGE %>
    <%= f.input :GENDER %>
    <%= f.input :MOBILE_NUMBER %>
    <%= f.input :STATUS %>
    <%= f.input :SESSION_ID %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tmp_contacts/edit.html.erb
<h1>Editing Tmp Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @tmp_contact %> |
<%= link_to 'Back', tmp_contacts_path %>

app/views/tmp_contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tmp Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Phone num</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Mobile number</th>
      <th>Status</th>
      <th>Session id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tmp_contacts.each do |tmp_contact| %>
      <tr>
        <td><%= tmp_contact.FIRSTNAME %></td>
        <td><%= tmp_contact.LASTNAME %></td>
        <td><%= tmp_contact.PHONE_NUM %></td>
        <td><%= tmp_contact.AGE %></td>
        <td><%= tmp_contact.GENDER %></td>
        <td><%= tmp_contact.MOBILE_NUMBER %></td>
        <td><%= tmp_contact.STATUS %></td>
        <td><%= tmp_contact.SESSION_ID %></td>
        <td><%= link_to 'Show', tmp_contact %></td>
        <td><%= link_to 'Edit', edit_tmp_contact_path(tmp_contact) %></td>
        <td><%= link_to 'Destroy', tmp_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tmp contact', new_tmp_contact_path %>

app/views/tmp_contacts/new.html.erb
<h1>New Tmp Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', tmp_contacts_path %>

app/views/tmp_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @tmp_contact.FIRSTNAME %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @tmp_contact.LASTNAME %>
</p>

<p>
  <strong>Phone num:</strong>
  <%= @tmp_contact.PHONE_NUM %>
</p>

<p>
  <strong>Age:</strong>
  <%= @tmp_contact.AGE %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @tmp_contact.GENDER %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @tmp_contact.MOBILE_NUMBER %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tmp_contact.STATUS %>
</p>

<p>
  <strong>Session id:</strong>
  <%= @tmp_contact.SESSION_ID %>
</p>

<%= link_to 'Edit', edit_tmp_contact_path(@tmp_contact) %> |
<%= link_to 'Back', tmp_contacts_path %>