config/routes.rb
Rails.application.routes.draw do
  resources :roles

  devise_for :users
  get 'home/index'
  root to: 'home#index'

  resources :confirm_shows
  resources :confirm_edits
  resources :confirm_deletes
  resources :ussd_logs
  resources :trackers
  resources :tmp_contacts
  resources :contacts
  
  devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end
  
  post 'create_user' => 'users#create', as: :create_user
  get '/users' => 'users#index'
  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/users/:id' => 'users#reset_password', :as => 'reset_password'
  
  
  
  
  
  get       'enable_contact'    =>  'contacts#enable_contact'
  get       'disable_contact'   =>  'contacts#disable_contact'
  
  get       'enable_log'    =>  'ussd_logs#enable_log'
  get       'disable_log'   =>  'ussd_logs#disable_log'
  
  get       'enable_user'    =>  'users#enable_user'
  get       'disable_user'   =>  'users#disable_user'
  
  get       'enable_role'    =>  'roles#enable_role'
  get       'disable_role'   =>  'roles#disable_role'
  
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
        belongs_to :role, class_name: "Role", foreign_key: :role_id
        
        def active_for_authentication?
          super && status
        end
        
         def self.to_csv
            attributes = %w{ fullname username email role_name }
            CSV.generate(headers: true) do |csv|
              csv << attributes
              
              joins(:role).select("users.*, roles.role_name").each do |user|
                csv << user.attributes.values_at(*attributes)
              end
              
            end
          end
        
              
        
        #filter by username
        def self.username_search(username)
         username = "%#{username}%"
         where('username LIKE ?', username)
        end
        
        #filter by network code
        def self.role_search(role)
         role = "%#{role}%"
         joins(:role).where('role_name LIKE ?', role)
        end
        
        def self.search_date(start, ended)
         where(created_at: "#{start} 00:00:00".."#{ended} 23:59:59")
        end
        
        
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /uusers
  # GET /uusers.json
  def index
    @users = User.all.paginate(page: params[:page], per_page: 5).order('id ASC')
    @roles = Role.all
    
    
    if params[:count]
      params[:count]
   else
     params[:count] = 10
   end
   
   if params[:page]
     page = params[:page].to_i
   else
     page = 1
   end
   
   if params[:per_page].present?
      # perpage = params[:per_page]
      @per_page = params[:per_page] || User.per_page || 10
      @users = User.paginate( :per_page => @per_page, :page => params[:page])
   else
     perpage = 10
   end
   @per_page = params[:per_page] || User.per_page || 10
   page = if params[:page]
            params[:page].to_i
           else
            1
           end
#            
   # per_page = 5
#    
   # offset = (page - 1) * per_page
   # limit = page * per_page
   # @array = *(offset...limit)

   if  params[:search_value] && params[:search_value].strip != ''
     
     if params[:search_param] == 'username'
       @users = User.username_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('id asc')
       
      elsif params[:search_param] == 'role'
        logger.info "We are INSidE THE NUMBER PARAM"
        @users = User.role_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('id asc')
        
   else
      @users = User.paginate(page: params[:page], per_page: params[:count]).order('id desc')
      @search_json = []
     end
     
      elsif params[:search_param] == 'date'
       start = (params["start_date"] + " " + "0:00:00")# Time.zone.parse(params["start_date"].to_s + " " + "0:00:00").utc # params["start_date"].to_s + "0:00:00"
       ended = params["end_date"] + " " + ("23:59:59") # Time.zone.parse(params["end_date"].to_s + " " + "23:59:59").utc # params["end_date"].to_s + "23:59:59"
       @users =User.search_date(start,ended).paginate(page: params[:page], per_page: params[:count]).order('id asc')

     
   end
   p "JSON ARRAY: #{@search_json}"
    
    
    
    
    respond_to do |format|
     format.html
     # format.xlsx
      format.csv { send_data @users.to_csv}
   end
   
  end


#enable user
 def enable_user
     user_id=params[:id]
    if User.update(user_id, :status => 1)
      redirect_to users_path, notice: 'User was successfully enabled.'
    end
 end

#disable user
 def disable_user
   user_id=params[:id]
  if User.update(user_id, :status => 0)
    redirect_to users_path, notice: 'User was successfully disabled.'
  end
 end


  # GET /uusers/1
  # GET /uusers/1.json
  def show
  end

  # GET /uusers/new
  def new
    @user = User.new
    @roles = Role.all
  end

  # GET /uusers/1/edit
  def edit
     @roles = Role.all
  end

  # POST /uusers
  # POST /uusers.json
  def create
    @roles = Role.all
    @user = User.new(user_params)
   

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  # reset_password
  def reset_password
    @roles = Role.all
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'Password was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end  

  # PATCH/PUT /uusers/1
  # PATCH/PUT /uusers/1.json
  def update
    @roles = Role.all
    respond_to do |format|
      if @user.update(user_params_edit)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uusers/1
  # DELETE /uusers/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
       params.require(:user).permit(:username, :email, :password, :password_confirmation, :status, :role_id, :username, :fullname)
    end
    
    def user_params_edit
       params.require(:user).permit(:username, :email, :status, :role_id, :username, :fullname)
    end
  
  
  # def new
  # end
# 
  # def create
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
<h3>Edit Contact</h3>

<div class="w3-container">
	<div class="w3-row">
		<div class="w3-col w3-container m4 col-sm-12"></div>
		<div class="w3-col w3-container m4 col-sm-12 ">
			<!-- <%= render 'form' %> -->
		</div>
		<div class="w3-col w3-container m4 col-sm-12 "></div>
		
	</div>
	
</div>

<!-- 
<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %> -->

app/views/users/_edit_form.html.erb
<%= simple_form_for(@user, url: update_user_path) do |f| %>
  <%= f.error_notification %>

<div class = "w3-card-4 w3-round-large"><br>
	  <div class="w3-container">
	  	<div class ="pull-left">
		   <%= f.input :fullname, required: true, input_html: { style: 'width: 200px' } %>
		</div>
		 
		 <div class ="pull-right">  
		   <%= f.input :username, required: true, input_html: { style: 'width: 200px' } %>
		 </div>
		 
		 <div class ="pull-left">
		   <%= f.input :email, required: true, email: true, input_html: { style: 'width: 200px' } %>
		 </div>
		 
		 <% if current_user.present? && current_user.role_id == 1 %>
			 <div class ="pull-right"> 
			   <%= f.input :role_id, collection: @roles, label_method: :role_name, value_method: :id, required: true, input_html: { style: 'width: 200px' } %>
			 </div>
		 <%else%>
		 	<div class ="pull-right"> 
			   <%= f.input :role_id, collection: @roles, label_method: :role_name, value_method: :id, required: true, disabled: true, input_html: { style: 'width: 200px' } %>
			 </div>
		  <%end%>
		 
		 <div class ="pull-left">
		   <%= f.input :password, input_html: { style: 'width: 200px' } %>
		 </div>
		 
		 <div class ="pull-right">		
		   <%= f.input :password_confirmation, input_html: { style: 'width: 200px' } %>
		 </div>
		  
		  
		   <%= f.input :status, :as=> :hidden, input_html: {value: 1 } %>
		   
		  <div style = "margin-top: 23%"> 
			 <%= f.submit "Update User", class: "w3-button w3-teal w3-round-large w3-hoverable w3-left" %>
			
			 <%= link_to ' Go Back', :back, class: "w3-blue w3-round-large w3-hoverable w3-button w3-right" %>
		  </div>
	  </div> 
	  <br>
 </div>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@user, url: create_user_path) do |f| %>
  <%= f.error_notification %>

<div class = "w3-card-4 w3-round-large"><br>
	<div class="w3-container">
	   <div class ="pull-left">
	      <%= f.input :fullname, required: true, input_html: { style: 'width: 200px' } %>
	   </div>
	   
	   <div class ="pull-right">
	    <%= f.input :username, required: true, input_html: { style: 'width: 200px' } %>
	   </div>
	   
	   <div class ="pull-left">
	    <%= f.input :email, required: true, email: true, input_html: { style: 'width: 200px' } %>
	   </div>
	   
	   <div class ="pull-right">
		 <%= f.input :role_id, collection: @roles, label_method: :role_name, value_method: :id, required: true, input_html: { style: 'width: 200px' } %>
	   </div>
	 	
	  <div class ="pull-left">
	   <%= f.input :password, required: true, input_html: { style: 'width: 200px' } %>
	  </div>
	
	 <div class ="pull-right">
	   <%= f.input :password_confirmation, required: true, input_html: { style: 'width: 200px' } %>
	 </div>
	   
	 
	   <%= f.input :status, :as=> :hidden, input_html: {value: 1 } %>
	   
	   <div style = "margin-top: 23%">
	    <%= f.submit "Create User", class: "w3-button w3-teal w3-round-large w3-hoverable w3-left" %>
	    <%= link_to ' Go Back', users_path, class: "w3-blue w3-round-large w3-hoverable w3-button w3-right" %>
	   </div>
	</div>
	<br>
</div>

<% end %>

app/views/users/_reset_password.html.erb
<%= simple_form_for(@user, url: update_user_path) do |f| %>
  <%= f.error_notification %>

<div class = "w3-card-4 w3-round-large"><br>
	  <div class="w3-container">
		   <%#= f.input :fullname, required: true %>
		   
		   <%#= f.input :username, required: true %>
		
		   <%#= f.input :email, required: true, email: true %>
		
		   <%= f.input :password, required: true %>
		
		
		   <%= f.input :password_confirmation, required: true %>
		   
		   <%#= f.input :role_id, collection: @roles, label_method: :role_name, value_method: :id, required: true %>
		   
		   <%#= f.input :status, :as=> :hidden, input_html: {value: 1 } %>
		   
		   
		   <%= f.submit "Update User", class: "w3-button w3-teal w3-round-large w3-hoverable w3-left" %>
		
		  <%= link_to ' Go Back', :back, class: "w3-blue w3-round-large w3-hoverable w3-button w3-right" %>
	
	  </div> 
	  <br>
 </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="w3-container" style = "margin-top: 5%">
	<h3>Edit User</h3>
	<div class="w3-row">
		<div class="w3-col w3-container m4 col-sm-12"></div>
		<div class="w3-col w3-container m4 col-sm-12 ">
			<span style = 'color:red'>NB: Please leave password fields blank if you don't want to change password! </span>
			<%= render 'edit_form' %>
		</div>
		<div class="w3-col w3-container m4 col-sm-12 "></div>
		
	</div>
	
</div>

app/views/users/index.html.erb
<div class="w3-row">
	<div class="w3-col w3-container m1 "></div>
	<div class="w3-col w3-container m10 ">
		<h3>Users</h3>
		
		<p style = 'text-align: center; font-family: tahoma; font-size: 15px;'>
		<b>Download:</b> <%= link_to "csv", users_path(format: "csv") %> 
		<!-- | <%= link_to "excel", contacts_path(format: "xlsx") %>  -->
		</p>
		
		 <%= form_tag users_path, method: :get, input_html:{display:"block"} do %>
			
			 <div class="radio_div">
			 	<b>Filter By:</b><br />
				<input id="username" type="radio" name="search_param" value="username" class = "w3-radio" /> Username 
					
				<input id="role" type="radio" name="search_param" value="role" class = "w3-radio" /> Role 
				
				<input id="date" type="radio" name="search_param" value="date" class = "w3-radio" /> Date 
					
			 </div>
				
									
			 <div class="form-inline" style = 'margin-top: 10px; margin-bottom: -20px'>
				<input id="search-field" class="hidden w3-input w3-border w3-round form-control"  name="search_value" />
				<input type="submit" id="search-field2" class=" hidden btn btn-primary " value="Search" >
			 </div>
			 
			 <div id="date_div" class="hidden form-inline" style ="margin-top: 27px; margin-bottom: -20px">
	                <!-- < div class="pull-left" style = 'margin-top: px; margin-bottom: px'> -->
	            <input type="text" class="form-control" data-provide='datepicker' name="start_date" id="date-field" placeholder="Start date "/>
	             <span class="add-on hidden" id = 'to'>to</span>
	                <!-- </div> -->
	                
	                <!-- <div class="pull-left" style = 'margin-top: px; margin-bottom: px'> -->
	            <input type="text" class="form-control" data-provide='datepicker' name="end_date" id="date-field2" placeholder="End date "/>
	                <!-- </div > -->
	            <input type="submit" id="search-field3" class=" hidden btn btn-primary" value="Search" style = "margin-left: 5px;" >

            </div>
				
		 <% end %>
		 
		 <div class="pull-right" style = 'margin-top: -2%'>
			<label class="">Display</label><br />
             <!-- <%#= select_tag :count, options_for_select([5,10,15,20,25,30], params[:count].to_i), :onchange => "if(this.value){ window.location='?count='+this.value ;}" %> -->
             <%= select_tag :per_page, options_for_select([10, 20, 30, 40,50, 70,100], params[:per_page].to_i),:onchange => "if(this.value){window.location='?per_page='+this.value;}", class: "w3-container  w3-bordered w3-round" %>
		 <br /><br />
		</div>
		
		<table class="w3-table-all w3-card-4 w3-small w3-hoverable table-condensed table-bordered">
		  <thead>
		    <tr class="w3-teal">
		      <th>Fullname</th>
		      <th>Username</th>
		      <th>Email</th>
		      <th>User Role</th>
		      <th style = "width: 150px">Date/Time</th>
		      
		      <% if current_user.present? && current_user.role_id == 1 %>
			     <th colspan="2" style="width: 15%">Options</th>
			      	
			      <%elsif current_user.present? && current_user.role_id == 2 %>
			      <th style = "width: 10px">Options</th>
			      	
			  <%end%>
		      
		    </tr>
		  </thead>
		
		  <tbody>
		    <% @users.each do |user| %>
		      <tr>
		        <td><%= user.fullname %></td>
		        <td><%= user.username %></td>
		        <td><%= user.email %></td>
		        <td><%= user.role.role_name if user.role %></td>
		        <td><%= user.created_at.strftime("%F %R") %></td>
		        
		        <td><%= link_to 'Edit', edit_user_path(user), class: 'w3-button  btn-default w3-blue w3-hover-blue w3-card-4 w3-ripple w3-round-large' %></td>
		        
		      <% if current_user.present? && current_user.role_id == 1 %>
		        <td>
			      <% if user.status == false %>
			         <%= link_to 'Enable', enable_user_path(:id => user.id), :class => 'w3-button btn-default w3-green w3-hover-green w3-card-4 w3-ripple w3-round-large'%>
			         <% else user.status == true %>
			         <%= link_to 'Disable', disable_user_path(:id => user.id), :class => 'w3-button btn-default w3-red w3-hover-red w3-card-4 w3-ripple w3-round-large', data: {confirm: 'Do you want to proceed?'}%>
			      <% end %>
		       </td>
		       <%end%>  
		        
		      </tr>
		    <% end %>
		  </tbody>
		</table>
		
		<%= will_paginate @users, renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: 'pagination-sm pull-right' %>
		 
		<br>
		
		<%= link_to '+', new_user_path, class: 'w3-button w3-teal w3-hover-blue w3-card-4 w3-ripple w3-circle' %> 
	<div>
	<div class="w3-col w3-container m1 "></div>

</div>

<script>
    $(document).ready(function() {
        $(".radio_div div input").click(function() {
            $("#date_div").addClass("hidden");
            $("#search-field").removeClass("hidden");
            $("#narrative_div").addClass("hidden");
            //$("#date_div").fadeIn('slow');
        });
        
        // filter by username
        $("#username").click(function() {
            if ($("#username").is(":checked")) {
                $("#search-field").attr("placeholder", "username");
                $("#search-field2").removeClass("hidden");
                $("#search-field").removeClass("hidden");
                $("#date-field").addClass("hidden");
                $("#date-field2").addClass("hidden");
                $("#search-field3").addClass("hidden")
                $("#to").addClass("hidden");
            }
        });
        
        // filter by role
        $("#role").click(function() {
            if ($("#role").is(":checked")) {
                $("#search-field").attr("placeholder", "role");
                $("#search-field2").removeClass("hidden");
                $("#search-field").removeClass("hidden");
                $("#date-field").addClass("hidden");
                $("#date-field2").addClass("hidden");
                $("#search-field3").addClass("hidden")
                $("#to").addClass("hidden");
            }
        });
       
        //////////////////////////clicking on filter by date
        $("#date").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").addClass("hidden");
            $("#search-field").addClass("hidden");
            $("#search-field3").removeClass("hidden");
            $("#to").removeClass("hidden");
            //$("#date_div").fadeIn('slow');
            //}
        });
        
        $("#date-field").click(function() {
           // if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            // $("#search-field3").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field2").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field3").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        
        
        ///////////////////////////////////////////////////
        $.fn.datepicker.noConflict = function() {
            $.fn.datepicker = old;
            return this;
        };
        ////////////////////////////////////////////////////
        $(function() {
            $('#date-field').datepicker({
                dateFormat : 'yy-mm-dd'
            }).val();
        });
        //////////////////////////////////////////////////////
        $(function() {
            $('#date-field2').datepicker({
                dateFormat : 'yy-mm-dd'
            });
        });
       
        
        ////////////////////////////////////////////////////////////////////////////
        $("#phone_number").click(function() {
            if ($("#phone_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Mobile number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
                $("#search-field2").removeClass("hidden")
            }
        });
        $("#recipient_number").click(function() {
            if ($("#recipient_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Recipient Number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
            }
        });
        
        
     
        // ///////////////////////////////////////////////////
        // $.fn.datepicker.noConflict = function() {
            // $.fn.datepicker = old;
            // return this;
        // };
        // ////////////////////////////////////////////////////
        // $(function() {
            // $('#date-field').datepicker({
                // dateFormat : 'yy-mm-dd'
            // });
        // });
        // //////////////////////////////////////////////////////
        // $(function() {
            // $('#date-field2').datepicker({
                // dateFormat : 'yy-mm-dd'
            // });
        // });
//         
        $('#csv').click(function() {
            console.log('works!');
            $('#csv_perpage').val($('#record').val());
            $('#csv_page').val($('li.active span').html());
            $('#csv_submit').click();
            console.log('works!');
        });
        /////////////////////////////////////////////////////////////
        $('#excel').click(function() {
            $('#excel_perpage').val($('#record').val());
            $('#excel_page').val($('li.active span').html());
            $('#excel_submit').click();
        });
    });
</script>


app/views/users/new.html.erb
<div class="w3-container" style = "margin-top: 5%">
	<h3>Add User</h3>
	<div class="w3-row">
		<div class="w3-col w3-container m4 col-sm-12"></div>
		<div class="w3-col w3-container m4 col-sm-12 ">
			<%= render 'form' %>
		</div>
		<div class="w3-col w3-container m4 col-sm-12 "></div>
		
	</div>
	
</div>

app/views/users/show.html.erb
<p>
  <strong>fullname:</strong>
  <%= @user.fullname %>
</p>

<p>
  <strong>username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role.role_name if @user.role %>
</p>