config/routes.rb
Rails.application.routes.draw do
  resources :roles

  devise_for :users
  get 'home/index'
  root to: 'home#index'

  resources :confirm_shows
  resources :confirm_edits
  resources :confirm_deletes
  resources :ussd_logs
  resources :trackers
  resources :tmp_contacts
  resources :contacts
  
  devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end
  
  post 'create_user' => 'users#create', as: :create_user
  get '/users' => 'users#index'
  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/users/:id' => 'users#reset_password', :as => 'reset_password'
  
  
  
  
  
  get       'enable_contact'    =>  'contacts#enable_contact'
  get       'disable_contact'   =>  'contacts#disable_contact'
  
  get       'enable_log'    =>  'ussd_logs#enable_log'
  get       'disable_log'   =>  'ussd_logs#disable_log'
  
  get       'enable_user'    =>  'users#enable_user'
  get       'disable_user'   =>  'users#disable_user'
  
  get       'enable_role'    =>  'roles#enable_role'
  get       'disable_role'   =>  'roles#disable_role'
  
  
  

end

app/models/role.rb
class Role < ActiveRecord::Base
  
  has_many :users
  
  def self.to_csv
     attributes = %w{ role_name }
     CSV.generate(headers: true) do |csv|
     csv << attributes
              
     all.each do |role|
     csv << role.attributes.values_at(*attributes)
      end
              
     end    
  end
  
  
  #filter by username
  def self.role_name_search(role_name)
    role_name = "%#{role_name}%"
    where('role_name LIKE ?', role_name)
  end
        
 def self.search_date(start, ended)
      where(created_at: "#{start} 00:00:00".."#{ended} 23:59:59")
  end
  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all.paginate(page: params[:page], per_page: 5).order('id desc')
    
     #search
   if params[:count]
      params[:count]
   else
     params[:count] = 10
   end
   
   if params[:page]
     page = params[:page].to_i
   else
     page = 1
   end
   
   if params[:per_page].present?
      # perpage = params[:per_page]
      @per_page = params[:per_page] || Role.per_page || 10
      @roles = Role.paginate( :per_page => @per_page, :page => params[:page])
   else
     perpage = 10
   end
   @per_page = params[:per_page] || Role.per_page || 10
   page = if params[:page]
            params[:page].to_i
           else
            1
           end
#            
   # per_page = 5
#    
   # offset = (page - 1) * per_page
   # limit = page * per_page
   # @array = *(offset...limit)

   if  params[:search_value] && params[:search_value].strip != ''
     
     if params[:search_param] == 'role_name'
       @roles = Role.role_name_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('id asc')
       
      elsif params[:search_param] == 'lastname'
        logger.info "We are INSIDE THE NUMBER PARAM"
        @roles = Role.lastname_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('ID asc')
        
     else
      @roles = Role.paginate(page: params[:page], per_page: params[:count]).order('ID desc')
      @search_json = []
     end
     
   elsif params[:search_param] == 'date'
       start = (params["start_date"] + " " + "0:00:00")# Time.zone.parse(params["start_date"].to_s + " " + "0:00:00").utc # params["start_date"].to_s + "0:00:00"
       ended = params["end_date"] + " " + ("23:59:59") # Time.zone.parse(params["end_date"].to_s + " " + "23:59:59").utc # params["end_date"].to_s + "23:59:59"
       @roles =Role.search_date(start,ended).paginate(page: params[:page], per_page: params[:count]).order('ID asc')

     
   end
   p "JSON ARRAY: #{@search_json}"
    
    
    respond_to do |format|
      format.html
      format.csv { send_data @roles.to_csv}
    end
    
  end


  #enable role 
 def enable_role
     role_id=params[:id]
    if Role.update(role_id, :status => 1)
      redirect_to roles_path, notice: 'Role was successfully enabled.'
    end
 end

#disable role
 def disable_role
   role_id=params[:id]
  if Role.update(role_id, :status => 0)
    redirect_to roles_path, notice: 'Role was successfully disabled.'
  end
 end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to roles_path, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to roles_path, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:role_name)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= simple_form_for(@role) do |f| %>
  <%= f.error_notification %>

<div class = "w3-card-4 w3-round-large"><br>
	  <div class="w3-container">
	    <%= f.input :role_name %>
	    <%= f.input :status, :class => "w3-radio", :as => :hidden %>
	    
	    <%= link_to 'Back', roles_path, class: "w3-button w3-teal w3-round-large w3-hoverable w3-left" %>
	    <%= f.button :submit, class: "w3-blue w3-round-large w3-hoverable w3-button w3-right" %>
	  </div>
	  
	 <br />
</div>

<% end %>

app/views/roles/edit.html.erb
<!-- <h1>Editing Role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %> -->
<div class="w3-container" style = "margin-top: 5%">
	<h3>Edit Role</h3>
	<div class="w3-row">
		<div class="w3-col w3-container m4 col-sm-12"></div>
		<div class="w3-col w3-container m4 col-sm-12 ">
			<%= render 'form' %>
		</div>
		<div class="w3-col w3-container m4 col-sm-12 "></div>
		
	</div>
	
</div>

app/views/roles/index.html.erb
<div class="w3-row">
	<div class="w3-col w3-container m3 "></div>
	<div class="w3-col w3-container m6 ">
		<h3>Roles</h3>
		<p style = 'text-align: center; font-family: tahoma; font-size: 15px;'>
		<b>Download:</b> <%= link_to "csv", roles_path(format: "csv") %> 
		<!-- | <%= link_to "excel", contacts_path(format: "xlsx") %>  -->
		</p>
		
		 <%= form_tag roles_path, method: :get, input_html:{display:"block"} do %>
			
			 <div class="radio_div">
			 	<b>Filter By:</b><br />
				<input id="role_name" type="radio" name="search_param" value="role_name" class = "w3-radio" /> Role Name
										
			    <input id="date" type="radio" name="search_param" value="date" class = "w3-radio" /> Date <br />
			 </div>
				
									
			 <div class="form-inline" style = 'margin-top: 10px; margin-bottom: -20px'>
				<input id="search-field" class="hidden w3-input w3-border w3-round form-control"  name="search_value" />
				<input type="submit" id="search-field2" class=" hidden btn btn-primary " value="Search" >
			 </div>
			 
			 <div id="date_div" class="hidden form-inline" style ="margin-top: 27px; margin-bottom: -20px">
	                <!-- < div class="pull-left" style = 'margin-top: px; margin-bottom: px'> -->
	           <input type="text" class="form-control" data-provide='datepicker' name="start_date" id="date-field" placeholder="Start date "/>
	             <span class="add-on hidden" id = 'to'>to</span>
	                <!-- </div> -->
	                
	                <!-- <div class="pull-left" style = 'margin-top: px; margin-bottom: px'> -->
	           <input type="text" class="form-control" data-provide='datepicker' name="end_date" id="date-field2" placeholder="End date "/>
	                <!-- </div > -->
	           <input type="submit" id="search-field3" class=" hidden btn btn-primary" value="Search" style = "margin-left: 5px;" >

            </div>
				
		 <% end %>
		 
		 <div class="pull-right" style = 'margin-top: -5%'>
			<label class="">Display</label><br />
             <!-- <%#= select_tag :count, options_for_select([5,10,15,20,25,30], params[:count].to_i), :onchange => "if(this.value){ window.location='?count='+this.value ;}" %> -->
             <%= select_tag :per_page, options_for_select([5, 10, 15], params[:per_page].to_i),:onchange => "if(this.value){window.location='?per_page='+this.value;}", class: "w3-container  w3-bordered w3-round" %>
		 <br /><br />
		</div>
		
		<table class="w3-table-all w3-card-4 w3-small w3-hoverable table-condensed table-bordered" >
			  <thead>
			    <tr class="w3-teal">
			      <th>s/n</th>
			      <th>Role name</th>
			      <th style = "width: 150px">Date/Time</th>
			      <th colspan="2" style="width: 10%">Options</th>
			    </tr>
			  </thead>
			
			  <tbody>
			    <% @roles.each_with_index do |role, index| %>
			      <tr>
			      	<td><%= "#{index+1}" %></td>
			        <td><%= role.role_name %></td>
			       <td><%= role.created_at.strftime("%F %R") %></td>
			        <td><%= link_to 'Edit', edit_role_path(role), class: 'w3-button  btn-default w3-blue w3-hover-blue w3-card-4 w3-ripple w3-round-large' %></td>
			        <!-- <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
			      <td>
			       <% if role.status == false %>
			           <%= link_to 'Enable', enable_role_path(:id => role.id), :class => 'w3-button btn-default w3-green w3-hover-green w3-card-4 w3-ripple w3-round-large'%>
			            <% else role.status == true %>
			            <%= link_to 'Disable', disable_role_path(:id => role.id), :class => 'w3-button btn-default w3-red w3-hover-red w3-card-4 w3-ripple w3-round-large', data: {confirm: 'Do you want to proceed?'}%>
			       <% end %>
		          </td>
			      
			      </tr>
			    <% end %>
			  </tbody>
			</table>
			<%= will_paginate @roles, renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: 'pagination-sm pull-right' %>
		
		<br />
		<%= link_to '+', new_role_path, class: 'w3-button w3-teal w3-hover-blue w3-card-4 w3-ripple w3-circle' %>
	</div>
	<div class="w3-col w3-container m3 "></div>
	
</div>


<script>
    $(document).ready(function() {
        $(".radio_div div input").click(function() {
            $("#date_div").addClass("hidden");
            $("#search-field").removeClass("hidden");
            $("#narrative_div").addClass("hidden");
            //$("#date_div").fadeIn('slow');
        });
        
        // filter by username
        $("#role_name").click(function() {
            if ($("#role_name").is(":checked")) {
                $("#search-field").attr("placeholder", "role name");
                $("#search-field2").removeClass("hidden")
                $("#search-field").removeClass("hidden");
                $("#date-field").addClass("hidden");
                $("#date-field2").addClass("hidden");
                $("#search-field3").addClass("hidden")
                $("#to").addClass("hidden");
            }
        });
        
        //////////////////////////clicking on filter by date
        $("#date").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field2").addClass("hidden");
            $("#search-field").addClass("hidden");
            $("#search-field3").removeClass("hidden");
            $("#to").removeClass("hidden");
            //$("#date_div").fadeIn('slow');
            //}
        });
        
        $("#date-field").click(function() {
           // if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            // $("#search-field3").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        $("#date-field2").click(function() {
            //if ($("#date").is(":checked")){
            $("#date_div").removeClass("hidden");
            $("#search-field").addClass("hidden");
            $("#date-field").removeClass("hidden");
            $("#date-field2").removeClass("hidden");
            $("#search-field3").removeClass("hidden")
            //$("#date_div").fadeIn('slow');
            //}
        });
        
        
        ///////////////////////////////////////////////////
        $.fn.datepicker.noConflict = function() {
            $.fn.datepicker = old;
            return this;
        };
        ////////////////////////////////////////////////////
        $(function() {
            $('#date-field').datepicker({
                dateFormat : 'yy-mm-dd'
            }).val();
        });
        //////////////////////////////////////////////////////
        $(function() {
            $('#date-field2').datepicker({
                dateFormat : 'yy-mm-dd'
            });
        });
        ////////////////////////////////////////////////////////////////////////////
        $("#phone_number").click(function() {
            if ($("#phone_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Mobile number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
                $("#search-field2").removeClass("hidden")
            }
        });
        $("#recipient_number").click(function() {
            if ($("#recipient_number").is(":checked")) {
                $("#search-field").attr("placeholder", "Recipient Number");
                $("#date_div").addClass("hidden");
                $("#search-field").removeClass("hidden");
            }
        });
        
        
     
        // ///////////////////////////////////////////////////
        // $.fn.datepicker.noConflict = function() {
            // $.fn.datepicker = old;
            // return this;
        // };
        // ////////////////////////////////////////////////////
        // $(function() {
            // $('#date-field').datepicker({
                // dateFormat : 'yy-mm-dd'
            // });
        // });
        // //////////////////////////////////////////////////////
        // $(function() {
            // $('#date-field2').datepicker({
                // dateFormat : 'yy-mm-dd'
            // });
        // });
//         
        $('#csv').click(function() {
            console.log('works!');
            $('#csv_perpage').val($('#record').val());
            $('#csv_page').val($('li.active span').html());
            $('#csv_submit').click();
            console.log('works!');
        });
        /////////////////////////////////////////////////////////////
        $('#excel').click(function() {
            $('#excel_perpage').val($('#record').val());
            $('#excel_page').val($('li.active span').html());
            $('#excel_submit').click();
        });
    });
</script>

app/views/roles/new.html.erb
<div class="w3-container" style = "margin-top: 5%">
	<h3>Add Role</h3>
	<div class="w3-row">
		<div class="w3-col w3-container m4 col-sm-12"></div>
		<div class="w3-col w3-container m4 col-sm-12 ">
			<%= render 'form' %>
		</div>
		<div class="w3-col w3-container m4 col-sm-12 "></div>
		
	</div>
	
</div>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role name:</strong>
  <%= @role.role_name %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>