config/routes.rb
Rails.application.routes.draw do
  resources :roles

  devise_for :users
  get 'home/index'
  root to: 'home#index'

  resources :confirm_shows
  resources :confirm_edits
  resources :confirm_deletes
  resources :ussd_logs
  resources :trackers
  resources :tmp_contacts
  resources :contacts
  
  devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end
  
  post 'create_user' => 'users#create', as: :create_user
  get '/users' => 'users#index'
  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/users/:id' => 'users#reset_password', :as => 'reset_password'
  
  
  
  
  
  get       'enable_contact'    =>  'contacts#enable_contact'
  get       'disable_contact'   =>  'contacts#disable_contact'
  
  get       'enable_log'    =>  'ussd_logs#enable_log'
  get       'disable_log'   =>  'ussd_logs#disable_log'
  
  get       'enable_user'    =>  'users#enable_user'
  get       'disable_user'   =>  'users#disable_user'
  
  get       'enable_role'    =>  'roles#enable_role'
  get       'disable_role'   =>  'roles#disable_role'
  
  
  

end

app/models/confirm_delete.rb
class ConfirmDelete < ActiveRecord::Base
end

app/models/confirm_edit.rb
class ConfirmEdit < ActiveRecord::Base
end

app/models/confirm_show.rb
class ConfirmShow < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
     validates :FIRSTNAME, presence: true
     validates :LASTNAME, presence: true
     validates :PHONE_NUM, presence: true
     validates :MOBILE_NUMBER, presence: true
     validates :AGE, presence: true
     validates :GENDER, presence: true
      
    
  def self.to_csv
    attributes = %w{FIRSTNAME LASTNAME PHONE_NUM MOBILE_NUMBER AGE GENDER}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      
      all.each do |contact|
        csv << contact.attributes.values_at(*attributes)
      end
      
    end
  end
  
  
  #filter by firstname
  def self.firstname_search(firstname)
   firstname = "%#{firstname}%"
   where('FIRSTNAME LIKE ?', firstname)
  end
  
  #filter by lastname
  def self.lastname_search(lastname)
   lastname = "%#{lastname}%"
   where('LASTNAME LIKE ?', lastname)
  end
  
  
  def self.search_date(start, ended)
      where(CREATED_AT: "#{start} 00:00:00".."#{ended} 23:59:59")
  end
  
  
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  
  has_many :users
  
  def self.to_csv
     attributes = %w{ role_name }
     CSV.generate(headers: true) do |csv|
     csv << attributes
              
     all.each do |role|
     csv << role.attributes.values_at(*attributes)
      end
              
     end    
  end
  
  
  #filter by username
  def self.role_name_search(role_name)
    role_name = "%#{role_name}%"
    where('role_name LIKE ?', role_name)
  end
        
 def self.search_date(start, ended)
      where(created_at: "#{start} 00:00:00".."#{ended} 23:59:59")
  end
  
end

app/models/tmp_contact.rb
class TmpContact < ActiveRecord::Base
end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
        belongs_to :role, class_name: "Role", foreign_key: :role_id
        
        def active_for_authentication?
          super && status
        end
        
         def self.to_csv
            attributes = %w{ fullname username email role_name }
            CSV.generate(headers: true) do |csv|
              csv << attributes
              
              joins(:role).select("users.*, roles.role_name").each do |user|
                csv << user.attributes.values_at(*attributes)
              end
              
            end
          end
        
              
        
        #filter by username
        def self.username_search(username)
         username = "%#{username}%"
         where('username LIKE ?', username)
        end
        
        #filter by network code
        def self.role_search(role)
         role = "%#{role}%"
         joins(:role).where('role_name LIKE ?', role)
        end
        
        def self.search_date(start, ended)
         where(created_at: "#{start} 00:00:00".."#{ended} 23:59:59")
        end
        
        
  
end

app/models/ussd_log.rb
class UssdLog < ActiveRecord::Base
    
    validates :msg_type, presence: true
    validates :service_key, presence: true
    validates :msg_type, presence: true
    validates :session_id, presence: true
    validates :mobile_num, presence: true
    validates :ussd_body, presence: true
    validates :nw_code, presence: true
    
  
  def self.to_csv
    attributes = %w{msg_type service_key session_id mobile_num ussd_body nw_code}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      
      all.each do |contact|
        csv << contact.attributes.values_at(*attributes)
      end
      
    end
  end
  
  
  #filter by message type
  def self.msg_type_search(msg_type)
   msg_type = "%#{msg_type}%"
   where('msg_type LIKE ?', msg_type)
  end
  
  #filter by network code
  def self.nw_code_search(nw_code)
   nw_code = "%#{nw_code}%"
   where('nw_code LIKE ?', nw_code)
  end
  
  
  def self.search_date(start, ended)
      where(created_at: "#{start} 00:00:00".."#{ended} 23:59:59")
  end
  
  
end

app/models/uuser.rb
class Uuser < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tmp_contacts_helper.rb
module TmpContactsHelper
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/ussd_logs_helper.rb
module UssdLogsHelper
end

app/helpers/uusers_helper.rb
module UusersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}", :style => "margin-top: 0.6%" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- <ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <%= render 'layouts/navigation_links' %>
</ul> -->

<!-- <div class="w3-top w3-bar w3-blue w3-border w3-card-4 w3-round w3-large">
	<%= link_to 'Home', root_path, class: 'w3-bar-item w3-button w3-hover-teal' %>
	<%= render 'layouts/navigation_links' %>
	
</div> -->

<div class="w3-bar w3-blue w3-border w3-card-4 w3-round w3-large">
    <%= link_to 'Home', root_path, class: 'w3-bar-item w3-button w3-hover-teal' %>
	<%= render 'layouts/navigation_links' %>
	
    <div class="w3-dropdown-hover w3-right">
      <button class="w3-button">
      	<% if current_user.present? && current_user.role_id? %>
          <%= current_user.username %>
        <% end %>
        <span class="caret"></span>
      </button>
      <div class="w3-dropdown-content w3-bar-block w3-card-4" style = 'margin-left: -5%; width: 50px'>
      	<% if current_user.present? && current_user.role_id == 1 %>
      	 <%= link_to 'View Users',  users_path, class: "w3-bar-item w3-button w3-small w3-hover-blue" %>
      	 <%= link_to 'View Roles',  roles_path, class: "w3-bar-item w3-button w3-small w3-hover-blue" %>
      	<%end%>
      	
      	<%= link_to 'Edit Profile',  edit_user_path(current_user), class: "w3-bar-item w3-button w3-small w3-hover-blue" %>
        <%= link_to 'Log Out',  destroy_user_session_path, method: :delete, class: "w3-bar-item w3-button w3-small w3-hover-blue" %>

      </div>
    </div>
  </div>

 <br />


 

app/views/layouts/_navigation_links.html.erb
<%= link_to 'Contacts', contacts_path, class: 'w3-bar-item w3-button w3-hover-teal ' %>
<%= link_to 'Logs', ussd_logs_path, class: 'w3-bar-item w3-button w3-hover-teal' %>
<%#= link_to 'Users', users_path, class: 'w3-bar-item w3-button w3-hover-teal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ussd Portal" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ussd Portal" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	<div class="w3-cell-row">
  		<div class="w3-top">
	  		<% if user_signed_in? %> 
	  	      <%= render 'layouts/navigation' %>
	  	     <%end%>
  		</div>
  		
   	  <div class="w3-container" style = 'margin-top: 3%'>
   	  	
   	  	<div class="w3-row">
   	  	    <%= render 'layouts/messages' %>
   	  	</div>
   	  	 
   	  <%= yield %>
   	  		
   	  </div>
      
    </div>
  </body>
</html>